#!/bin/bash

#######################################################################################
# Before you run this, you need to enable multiverse packages and add                 #
#   deb http://ppa.launchpad.net/shiki/mediainfo/ubuntu YOUR_UBUNTU_VERSION_HERE main #
#   deb-src http://ppa.launchpad.net/shiki/mediainfo/ubuntu YOUR_UBUNTU_VERSION_HERE. #
# to /etc/apt/sources.list															  #
#######################################################################################

# Uninstall x264, libx264-dev, and ffmpeg if they are already installed.
sudo apt-get remove ffmpeg x264 libx264-dev

# Get all of the packages you will need to install FFmpeg and x264
sudo apt-get update
sudo apt-get install build-essential git-core checkinstall yasm texi2html \
    libfaac-dev libjack-jackd2-dev libmp3lame-dev libopencore-amrnb-dev \
    libopencore-amrwb-dev libsdl1.2-dev libtheora-dev libva-dev libvdpau-dev \
    libvorbis-dev libvpx-dev libx11-dev libxfixes-dev libxvidcore-dev zlib1g-dev

# Get the current source files, compile, and install x264.
cd
git clone git://git.videolan.org/x264.git
cd x264
./configure
sudo make install
sudo checkinstall --pkgname=x264 --pkgversion="3:$(./version.sh | \
    awk -F'[" ]' '/POINT/{print $4"+git"$5}')" --backup=no --deldoc=yes \
    --fstrans=no --default

# Get the most current source files, compile, and install FFmpeg.
cd
git clone git://git.ffmpeg.org/ffmpeg.git
cd ffmpeg
./configure --enable-gpl --enable-version3 --enable-nonfree --enable-postproc \
    --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb \
    --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis \
    --enable-libvpx --enable-libx264 --enable-libxvid --enable-x11grab
sudo make install
sudo checkinstall --pkgname=ffmpeg --pkgversion="5:$(./version.sh)" --backup=no \
    --deldoc=yes --fstrans=no --default
hash x264 ffmpeg ffplay ffprobe

# This is a useful tool included with FFmpeg that rearranges a file with H.264 video, "such that the moov atom is in front of the data, thus facilitating network streaming". Basically, it allows web movies to start playing before they are completely downloaded. Usage: qt-faststart input.foo output.foo
cd ~/ffmpeg
make tools/qt-faststart
sudo checkinstall --pkgname=qt-faststart --pkgversion="$(./version.sh)" --backup=no \
    --deldoc=yes --fstrans=no --default install -D -m755 tools/qt-faststart \
    /usr/local/bin/qt-faststart
    
# Install mediainfo library
sudo apt-get install mediainfo

# Install imagemagick library
sudo apt-get install imagemagick

# Install Ruby and RubyGems
sudo apt-get install ruby rdoc rubygems

# Install the RightAws gem
sudo gem install right_aws